### ISSUE TITLE
Merge master with Rewrite branch

### ISSUE THREAD

**Issue by SpiderMath** [hasib-rashid/Falcon#25]
I don't really think showing people old code will be cool. Either merge the Rewrite Branch to Master OR you could make Rewrite branch the master branch, because both will be pretty much fixing the issue I wanted to fix :smile:

**Comment by hasib-rashid** [comment]
I am actually copy pasting the whole code of the master branch to the rewrrite but its written in typescript. Yeah I will be finishing that job in the rewrite branch and then merge it to the master branch. Consider this done by this week.

Keep doing Bug and Pull Requests <3

**Comment by SpiderMath** [comment]
Okay, understood.
